INSERT INTO users (user_id, username, bio, email, profile_photo_url) 
VALUES
(1, 'JohnDoe01', 'Software engineer passionate about open source and AI.', 'johndoe@example.com', 'https://picsum.photos/101'),
(2, 'JaneSmith02', 'Digital marketer with a love for creative content and design.', 'janesmith@example.com', 'https://picsum.photos/101'),
(3, 'DavidBrown03', 'Traveler and photographer capturing moments around the world.', 'davidbrown@example.com', 'https://picsum.photos/101'),
(4, 'EmilyDavis04', 'Content strategist focusing on SEO and web analytics.', 'emilydavis@example.com', 'https://picsum.photos/101'),
(5, 'MichaelWilson05', 'Entrepreneur and startup enthusiast building scalable solutions.', 'michaelwilson@example.com', 'https://picsum.photos/101'),
(6, 'SarahJohnson06', 'Writer and blogger sharing stories and reviews on lifestyle.', 'sarahjohnson@example.com', 'https://picsum.photos/101'),
(7, 'ChrisLee07', 'Web developer exploring new technologies and frameworks.', 'chrislee@example.com', 'https://picsum.photos/101'),
(8, 'LauraMartinez08', 'Data scientist with a focus on machine learning and AI models.', 'lauramartinez@example.com', 'https://picsum.photos/101'),
(9, 'JamesTaylor09', 'Business consultant helping companies grow through innovative solutions.', 'jamestaylor@example.com', 'https://picsum.photos/101'),
(10, 'PatriciaAnderson10', 'Creative director designing memorable experiences for brands.', 'patriciaanderson@example.com', 'https://picsum.photos/101'),
(11, 'RobertThomas11', 'Product manager with a passion for agile methodologies and UX.', 'robertthomas@example.com', 'https://picsum.photos/101'),
(12, 'LindaJackson12', 'Social media strategist focusing on engagement and content creation.', 'lindajackson@example.com', 'https://picsum.photos/101'),
(13, 'WilliamWhite13', 'Project manager specializing in team leadership and development.', 'williamwhite@example.com', 'https://picsum.photos/101'),
(14, 'ElizabethHarris14', 'UX/UI designer creating intuitive digital experiences.', 'elizabethharris@example.com', 'https://picsum.photos/101'),
(15, 'DavidClark15', 'AI engineer working on neural networks and deep learning.', 'davidclark@example.com', 'https://picsum.photos/101'),
(16, 'JenniferLewis16', 'Operations manager optimizing business processes and workflow.', 'jenniferlewis@example.com', 'https://picsum.photos/101'),
(17, 'CharlesRobinson17', 'Software architect with expertise in cloud computing and security.', 'charlesrobinson@example.com', 'https://picsum.photos/101'),
(18, 'SusanWalker18', 'Creative consultant helping brands express their identity through design.', 'susanwalker@example.com', 'https://picsum.photos/101'),
(19, 'JosephHall19', 'Marketing director focusing on digital strategy and brand awareness.', 'josephhall@example.com', 'https://picsum.photos/101'),
(20, 'KarenAllen20', 'Business analyst with a focus on market research and data analysis.', 'karenallen@example.com', 'https://picsum.photos/101'),
(21, 'KevinYoung21', 'Graphic designer creating visual content for print and digital media.', 'kevinyoung@example.com', 'https://picsum.photos/101'),
(22, 'MeganKing22', 'Public relations manager developing strategies to boost brand visibility.', 'meganking@example.com', 'https://picsum.photos/101'),
(23, 'JoshuaScott23', 'Full stack developer with a passion for building innovative web apps.', 'joshuascott@example.com', 'https://picsum.photos/101'),
(24, 'NancyWright24', 'HR specialist focusing on talent acquisition and employee engagement.', 'nancywright@example.com', 'https://picsum.photos/101'),
(25, 'BrianMartinez25', 'Operations lead optimizing logistics and warehouse management.', 'brianmartinez@example.com', 'https://picsum.photos/101'),
(26, 'AngelaPerez26', 'Financial analyst with a keen eye on investments and budgeting.', 'angelaperez@example.com', 'https://picsum.photos/101'),
(27, 'TimothyCarter27', 'Cybersecurity expert ensuring data protection and network security.', 'timothycarter@example.com', 'https://picsum.photos/101'),
(28, 'DorothyRodriguez28', 'Marketing specialist with a focus on email campaigns and social media.', 'dorothyrodriguez@example.com', 'https://picsum.photos/101'),
(29, 'EthanLee29', 'Photographer and videographer specializing in corporate and event media.', 'ethanlee@example.com', 'https://picsum.photos/101'),
(30, 'ChloeGonzalez30', 'Research analyst specializing in scientific data and trends.', 'chloegonzalez@example.com', 'https://picsum.photos/101'),
(31, 'SamuelPerez31', 'Supply chain manager ensuring efficiency in product distribution.', 'samuelperez@example.com', 'https://picsum.photos/101'),
(32, 'RebeccaNelson32', 'Software developer building apps for mobile and web platforms.', 'rebeccanelson@example.com', 'https://picsum.photos/101'),
(33, 'RyanCarter33', 'Systems administrator maintaining and optimizing enterprise IT systems.', 'ryancarter@example.com', 'https://picsum.photos/101'),
(34, 'AnnaMitchell34', 'Operations coordinator managing projects and budgets for clients.', 'annamitchell@example.com', 'https://picsum.photos/101'),
(35, 'SamuelThomas35', 'Machine learning engineer creating AI models for automation.', 'samuelthomas@example.com', 'https://picsum.photos/101'),
(36, 'JessicaWalker36', 'Brand strategist developing innovative marketing solutions.', 'jessicawalker@example.com', 'https://picsum.photos/101'),
(37, 'DanielAllen37', 'Web designer crafting user-friendly interfaces for websites.', 'danielallen@example.com', 'https://picsum.photos/101'),
(38, 'SophiaKing38', 'Event planner organizing corporate events and social gatherings.', 'sophiaking@example.com', 'https://picsum.photos/101'),
(39, 'JackEvans39', 'Database administrator managing large-scale data systems.', 'jackevans@example.com', 'https://picsum.photos/101'),
(40, 'OliviaTurner40', 'Research scientist conducting experiments in biochemistry.', 'oliviaturner@example.com', 'https://picsum.photos/101'),
(41, 'LucasHarris41', 'Social media consultant with a focus on branding and engagement.', 'lucasharris@example.com', 'https://picsum.photos/101'),
(42, 'MiaRoberts42', 'PR strategist working with major clients to craft their public image.', 'miaroberts@example.com', 'https://picsum.photos/101'),
(43, 'AidenYoung43', 'Digital artist creating animations and 3D visualizations.', 'aidenyoung@example.com', 'https://picsum.photos/101'),
(44, 'EllaWalker44', 'Account manager working with clients to optimize marketing strategies.', 'ellawalker@example.com', 'https://picsum.photos/101'),
(45, 'BenjaminLee45', 'Creative writer focused on storytelling and copywriting.', 'benjaminlee@example.com', 'https://picsum.photos/101'),
(46, 'NatalieMoore46', 'SEO specialist improving search engine rankings for businesses.', 'nataliemoore@example.com', 'https://picsum.photos/101'),
(47, 'ElijahBrown47', 'Mobile app developer building solutions for Android and iOS platforms.', 'elijahbrown@example.com', 'https://picsum.photos/101'),
(48, 'MeganClark48', 'User researcher gathering insights to improve digital products.', 'meganclark@example.com', 'https://picsum.photos/101'),
(49, 'IsaacWalker49', 'Data analyst interpreting data for business insights and reports.', 'isaacwalker@example.com', 'https://picsum.photos/101'),
(50, 'GraceYoung50', 'Public relations manager handling communications for brands.', 'graceyoung@example.com', 'https://picsum.photos/101'),
(51, 'HenryHall51', 'UX researcher focusing on improving user experience design.', 'henryhall@example.com', 'https://picsum.photos/101'),
(52, 'ZoeEvans52', 'Web developer creating responsive websites and web apps.', 'zoeevans@example.com', 'https://picsum.photos/101'),
(53, 'LeoWhite53', 'Cloud architect designing scalable and secure cloud infrastructures.', 'leowhite@example.com', 'https://picsum.photos/101'),
(54, 'ChloeMitchell54', 'Brand manager overseeing campaigns and market positioning.', 'chloemitchell@example.com', 'https://picsum.photos/101');



